# Generated by Django 4.2.5 on 2023-09-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='ISOCode',
            new_name='iso_code',
        ),
    ]
